### ISSUE TITLE
支持 Volar + vue@2？

### ISSUE THREAD

**Issue by ModyQyW** [satrong/uni-base-components-types#2]
能否支持 vue 2 呢？

**Comment by satrong** [comment]
这个与 vue 的版本没关系吧？

**Comment by ModyQyW** [comment]
安装依赖之后项目内文件列表如下。

<img width="176" alt="image" src="https://user-images.githubusercontent.com/31850793/176993642-f1510d7a-11f2-4148-80b4-2ac356502eaa.png">

`index.d.ts` 从 `vue` 导入了类型。

https://github.com/satrong/uni-base-components-types/blob/8e253ecf701fca9f53c46769ff3d074aaf820dce/index.d.ts#L1-L6

但是一些类型是 `vue@3` 独有的，比如 `DefineComponent`。在 `vue@2` 和 `uni-app` 组合使用的情况下，我在内部项目内试验过，无法得到正确的类型。

<img width="394" alt="image" src="https://user-images.githubusercontent.com/31850793/176993758-61640ed9-e8ad-42d6-b304-3990b98bceb2.png">

**Comment by satrong** [comment]
`view` 组件可能与原生的组件冲突，其它的组件时正常的吗？另外你用的是 Volar 吗？

**Comment by satrong** [comment]
vue 2 直接用 vetur + @dcloudio/uni-helper-json 不可以吗？

**Comment by ModyQyW** [comment]
> `view` 组件可能与原生的组件冲突，其它的组件时正常的吗？另外你用的是 Volar 吗？

不正常，用的是 Volar

<img width="317" alt="image" src="https://user-images.githubusercontent.com/31850793/176994513-99f395a9-c5fa-4bf1-a544-0c966af352a7.png">

<img width="552" alt="image" src="https://user-images.githubusercontent.com/31850793/176994558-c8b6071f-39b7-4db2-80d8-a52fd2c6a42d.png">

> vue 2 直接用 vetur + @dcloudio/uni-helper-json 不可以吗？

我这边所有 Vue 项目都上 Volar 了，所以我也不确定

**Comment by satrong** [comment]
我发布了一个beta版本，你安装测试看下行否
```bash
npm i uni-base-components-types@2.0.0-beta.0
```

**Comment by ModyQyW** [comment]
初步试了一下看着可以，非常感谢。
