### ISSUE TITLE
<Button> openType 类型补全 

### ISSUE THREAD

**Issue by zfowed** [satrong/uni-base-components-types#3]
不支持一些原始的开放接口嘛
![image](https://user-images.githubusercontent.com/23629388/177503036-4eeb04c8-47a1-4784-830d-fa9bb1119104.png)

**Comment by satrong** [comment]
![图片](https://user-images.githubusercontent.com/5283258/177514757-ded7235f-cfd9-44f9-8ba3-ce508bb46982.png)

因为类型是从 [@dcloudio/uni-helper-json](https://www.npmjs.com/package/@dcloudio/uni-helper-json) 中提取的，所以可能会有误差。

这个 `open-type` 是可以支持自定义类型吗？

**Comment by satrong** [comment]
你也可以尝试一下
```
:open-type="'getPhoneNumber' as any"
```
