### ISSUE TITLE
根据官方文档更新类型文件？

### ISSUE THREAD

**Issue by ModyQyW** [satrong/uni-base-components-types#4]
@dcloudio/uni-helper 最近更新在一年前，和文档相差较大。

目前我想根据官方文档更新类型文件并提交一个 PR，不知道是否愿意接受？

**Comment by ModyQyW** [comment]
Draft https://github.com/satrong/uni-base-components-types/pull/5

**Comment by ModyQyW** [comment]
Draft https://github.com/satrong/uni-base-components-types/pull/5

**Comment by satrong** [comment]
这样改动维护成本太高了。我有想过从官方的文档中提取类型，然后定期的自动更新，奈何没这精力😂

**Comment by ModyQyW** [comment]
如果你觉得 ok 的话可以让我来做这部分，我公司里刚好是有这方面需求的。

官方的文档太乱了，我之前也试过自动化，但是还不如人工来得快……😅

**Comment by satrong** [comment]
长远考虑这样不太好，目前我想的有两种方案：
1. 从官方文档抓取类型
2. 通过 ast 从源码中抓取类型

你可以对比一下这两种方案哪种比较靠谱，可以的话我们可以一起搞

**Comment by ModyQyW** [comment]
目前我认为当务之急是先人工更新一版定义，因为很多组件 prop 的类型、描述和文档对不上。Draft 就是为了完成这个目标而建的。

你想的两种方案我在做 uni-helper 相关的时候都有考虑过，但是工程量都很大并不亚于人工，主要是 FIX 很复杂，我认为两种方案都不是特别靠谱。目前 uni-helper 采用的是人工定期更新的策略。
